{% set python_min = '3.11' %}
{% set name = "hssm" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hssm-{{ version }}.tar.gz
  sha256: 70706738ff7bb150348ff0d256ae2c0df411dfd5e8f5b9b01aa9350e2c43a949

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13a0
    - numpy >=2.0.0
    - pymc >=5.21.0
    - arviz >=0.19.0
    - bambi >=0.15.0,<0.16.0
    - onnx >=1.16.0,<2.0.0
    - jax >=0.5.3
    - ssm-simulators >=0.10.2
    - huggingface_hub >=0.25.0
    - numpyro >=0.17.0
    - seaborn >=0.13.2
    - hddm-wfpt >=0.1.5
    - cloudpickle >=3.0.0
    - tqdm >=4.66.0
test:
  imports:
    - hssm
  # Temporarily not doing pip check because jaxlib version on conda-forge lags behind jax version
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://lnccbrown.github.io/HSSM/
  summary: Bayesian inference for hierarchical sequential sampling models.
  dev_url: https://github.com/lnccbrown/HSSM/
  license: LicenseRef-Brown-University-2023
  license_file: LICENSE

extra:
  recipe-maintainers:
    - digicosmos86
    - AlexanderFengler
