{% set name = "hssm" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hssm-{{ version }}.tar.gz
  sha256: 8689e3f361b1abcb6fcc6e66cc0d9d405d1ed50cbd3c1ec85bdd4ba1c3b62699

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<=3.12
    - poetry-core
    - pip
  run:
    - python >=3.10,<=3.12
    - pymc >=5.16.2,<5.17.0
    - arviz >=0.19.0
    - onnx >=1.16.0,<2.0.0
    - jax >=0.4.25,<0.5.0
    - ssm-simulators >=0.7.5,<0.8.0
    - huggingface_hub >=0.24.6,<0.25.0
    - bambi >=0.14.0,<0.15.0
    - numpyro >=0.15.2,<0.16.0
    - seaborn >=0.13.2,<0.14.0
    - hddm-wfpt >=0.1.4,<0.2.0
test:
  imports:
    - hssm
  # Temporarily not doing pip check because jaxlib version on conda-forge lags behind jax version
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://lnccbrown.github.io/HSSM/
  summary: Bayesian inference for hierarchical sequential sampling models.
  dev_url: https://github.com/lnccbrown/HSSM/
  license: LicenseRef-Brown-University-2023
  license_file: LICENSE

extra:
  recipe-maintainers:
    - digicosmos86
    - AlexanderFengler
